from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
import time

s = Service('usr/local/bin/chromedriver')
driver = webdriver.Chrome(service=s)
# Random.org testing
# driver.get("https://www.random.org/integers")

# # test 1
# time.sleep(1)
# num_nums = driver.find_element(By.CSS_SELECTOR, 'input[name="num"]')
# num_nums.clear()
# time.sleep(1)
# num_nums.send_keys("10")
# time.sleep(1)
# min_nums = driver.find_element(By.CSS_SELECTOR, 'input[name="min"]')
# min_nums.clear()
# min_nums.send_keys("3")
# time.sleep(1)
# max_nums = driver.find_element(By.CSS_SELECTOR, 'input[name="max"]')
# max_nums.clear()
# time.sleep(1)
# max_nums.send_keys("10000")
# reset_button = driver.find_element(By.CSS_SELECTOR, 'input[value="Reset Form"]')
# reset_button.click()
# time.sleep(2)

# # test 2
# num_numbers = driver.find_element(By.CSS_SELECTOR, 'input[name="num"]')
# num_numbers.clear()
# num_numbers.send_keys("125")
# time.sleep(1)
# min_nums = driver.find_element(By.CSS_SELECTOR, 'input[name="min"]')
# min_nums.clear()
# min_nums.send_keys("60")
# time.sleep(1)
# max_nums = driver.find_element(By.CSS_SELECTOR, 'input[name="max"]')
# max_nums.clear()
# max_nums.send_keys("10000")
# column_input = driver.find_element(By.CSS_SELECTOR, 'input[name="col"]')
# column_input.clear()
# column_input.send_keys("10")
# time.sleep(1)
# submit_button = driver.find_element(By.CSS_SELECTOR, 'input[value="Get Numbers"]')
# submit_button.click()
# time.sleep(3)
# driver.back()
# time.sleep(1)
# advance_button = driver.find_element(By.CSS_SELECTOR, 'input[value="Switch to Advanced Mode"]')
# advance_button.click()
# time.sleep(3)

# PHP Travels testing
driver.get('https://phptravels.com/demo/')
time.sleep(3)
pricing_button = driver.find_element(By.CSS_SELECTOR, 'a[class="jfHeader-menuListLink jfHeader-dynamicLink js-tracking js-myforms"')
pricing_button.click()
time.sleep(3)
driver.back()
time.sleep(2)
features_dropdown = driver.find_element(By.CSS_SELECTOR, 'a[class="jfHeader-menuListLink jfHeader-dynamicLink js-tracking"]')
features_dropdown.click()
time.sleep(2)
integrations_dropdown = driver.find_element(By.CSS_SELECTOR, 'a[class="jfHeader-menuListLink jfHeader-dynamicLink js-tracking js-integrations"]')
integrations_dropdown.click()
time.sleep(2)
company_dropdown = driver.find_element(By.CSS_SELECTOR, 'a[data-text-name="support"]')
company_dropdown.click()
time.sleep(2)

# test inputs
first_name = driver.find_element(By.CSS_SELECTOR, 'input[class="first_name input mb1"]')
first_name.send_keys("Andrew")
last_name = driver.find_element(By.CSS_SELECTOR, 'input[name="last_name"]')
last_name.send_keys("Winkler")
business_name = driver.find_element(By.CSS_SELECTOR, 'input[name="business_name"]')
business_name.send_keys("Winkler Enterprises")
email_address = driver.find_element(By.CSS_SELECTOR, 'input[name="email"]')
email_address.send_keys('turdman@fire.com')
time.sleep(7)
submit2_button = driver.find_element(By.CSS_SELECTOR, 'button[id="demo"]')
submit2_button.click()
time.sleep(3)

driver.quit()

# test socials
# php_facebook = driver.find_element(By.CSS_SELECTOR, 'a[href="https://www.facebook.com/phptravels"]')
# php_facebook.click()
# time.sleep(2)
# driver.back()
# php_twitter = driver.find_element(By.CSS_SELECTOR, 'a[href="https://twitter.com/phptravels"]')
# php_twitter.click()
# time.sleep(2)
# driver.back()
# php_linkedin = driver.find_element(By.CSS_SELECTOR, 'a[href="https://www.linkedin.com/company/phptravels/"]')
# php_linkedin.click()
# time.sleep(2)
# driver.back()
# php_youtube = driver.find_element(By.CSS_SELECTOR, 'a[href="https://www.twitter.com/phptravels"]')
# php_youtube.click()
# time.sleep(2)
# driver.back()
# php_instagram = driver.find_element(By.CSS_SELECTOR, 'a[href="https://www.instagram.com/phptravels/"]')
# php_instagram.click()
# time.sleep(2)
first_name = driver.find_element(By.CSS_SELECTOR, 'input[class="first_name input mb1"]')
first_name.send_keys("Andrew")
last_name = driver.find_element(By.CSS_SELECTOR, 'input[name="last_name"]')
last_name.send_keys("Winkler")
business_name = driver.find_element(By.CSS_SELECTOR, 'input[name="business_name"]')
business_name.send_keys("Winkler Enterprises")
email_address = driver.find_element(By.CSS_SELECTOR, 'input[name="email"]')
email_address.send_keys('turdman@fire.com')
time.sleep(7)
submit2_button = driver.find_element(By.CSS_SELECTOR, 'button[id="demo"]')
submit2_button.click()
time.sleep(3)

driver.quit()

